title: Galileyous OSCP Cheatsheets
description: "OSCP Cheatsheets"
author:
  name: "Galileyous"
  email: "galileyous@hotmail.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Galileyous"
year : "2022"
